<?php

namespace AppBundle\Repository;
use AppBundle\AppBundle;
use AppBundle\Entity\Theme;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function getAllTheme()
    {
        $qb = $this->createQueryBuilder("t");

        $qb->select("t.name, count(p) as numberOfPosts, t.id")
        ->innerJoin("t.posts", "p")
        ->groupBy("t.id");

        dump($qb->getDQL());

        return $qb->getQuery();
    }

}

